/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.myst;

/**
 *
 * @author Rodrigo
 */
public class CharacterPanel extends javax.swing.JPanel {

    /**
     * Creates new form CharacterPanel
     */
    public CharacterPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNombre = new javax.swing.JLabel();
        jHP = new javax.swing.JLabel();
        jMP = new javax.swing.JLabel();
        jAtaque = new javax.swing.JLabel();
        jDefensa = new javax.swing.JLabel();
        jSkill = new javax.swing.JLabel();
        jDSkill = new javax.swing.JLabel();
        jCSkill = new javax.swing.JLabel();
        jGold = new javax.swing.JLabel();
        jLoot = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Character"));

        jNombre.setText("Nombre: ");

        jHP.setText("HP: ");

        jMP.setText("MP: ");

        jAtaque.setText("Ataque: ");

        jDefensa.setText("Defensa: ");

        jSkill.setText("Skill: ");

        jDSkill.setText("Daño Skill: ");

        jCSkill.setText("Costo Skill: ");

        jGold.setText("Gold: ");

        jLoot.setText("Loot: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jHP)
                            .addComponent(jNombre))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jMP)
                            .addGap(29, 29, 29)))
                    .addComponent(jAtaque)
                    .addComponent(jDefensa))
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLoot)
                    .addComponent(jGold)
                    .addComponent(jSkill)
                    .addComponent(jDSkill)
                    .addComponent(jCSkill))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNombre)
                    .addComponent(jSkill))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHP)
                    .addComponent(jDSkill))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMP)
                    .addComponent(jCSkill))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAtaque)
                    .addComponent(jGold))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDefensa)
                    .addComponent(jLoot))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAtaque;
    private javax.swing.JLabel jCSkill;
    private javax.swing.JLabel jDSkill;
    private javax.swing.JLabel jDefensa;
    private javax.swing.JLabel jGold;
    private javax.swing.JLabel jHP;
    private javax.swing.JLabel jLoot;
    private javax.swing.JLabel jMP;
    private javax.swing.JLabel jNombre;
    private javax.swing.JLabel jSkill;
    // End of variables declaration//GEN-END:variables
}
