/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.myst;

/**
 *
 * @author Rodrigo
 */
public class CharacterPanel extends javax.swing.JPanel {

    /**
     * Creates new form CharacterPanel
     */
    public CharacterPanel(Personaje p) {
        initComponents();
        lblNombre.setText("Nombre: " + p.name);
        lblHP.setText("HP: " + p.hp);
        lblMP.setText("MP: " + p.mp);
        lblAtaque.setText("Ataque: " + p.attack);
        lblDefensa.setText("Defensa: " + p.defense);
        lblSkill.setText("Skill: " + p.skill);
        lblSkillDamage.setText("Daño Skill: " + p.damage);
        lblSkillCost.setText("Costo Skill: " + p.mp_cost);
        lblGold.setText("Gold: " + p.gold);
        lblLoot.setText("Loot: " + p.loot);
    }
    
    public void setDatos(Personaje p) {
        lblNombre.setText("Nombre: " + p.name);
        lblHP.setText("HP: " + p.hp);
        lblMP.setText("MP: " + p.mp);
        lblAtaque.setText("Ataque: " + p.attack);
        lblDefensa.setText("Defensa: " + p.defense);
        lblSkill.setText("Skill: " + p.skill);
        lblSkillDamage.setText("Daño Skill: " + p.damage);
        lblSkillCost.setText("Costo Skill: " + p.mp_cost);
        lblGold.setText("Gold: " + p.gold);
        lblLoot.setText("Loot: " + p.loot);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblHP = new javax.swing.JLabel();
        lblMP = new javax.swing.JLabel();
        lblAtaque = new javax.swing.JLabel();
        lblDefensa = new javax.swing.JLabel();
        lblSkill = new javax.swing.JLabel();
        lblSkillDamage = new javax.swing.JLabel();
        lblSkillCost = new javax.swing.JLabel();
        lblGold = new javax.swing.JLabel();
        lblLoot = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Character"));

        lblNombre.setText("Nombre: ");

        lblHP.setText("HP: ");

        lblMP.setText("MP: ");

        lblAtaque.setText("Ataque: ");

        lblDefensa.setText("Defensa: ");

        lblSkill.setText("Skill: ");

        lblSkillDamage.setText("Daño Skill: ");

        lblSkillCost.setText("Costo Skill: ");

        lblGold.setText("Gold: ");

        lblLoot.setText("Loot: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHP)
                            .addComponent(lblNombre)))
                    .addComponent(lblAtaque)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblMP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDefensa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLoot)
                    .addComponent(lblGold)
                    .addComponent(lblSkill)
                    .addComponent(lblSkillDamage)
                    .addComponent(lblSkillCost))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblSkill))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHP)
                    .addComponent(lblSkillDamage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMP)
                    .addComponent(lblSkillCost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAtaque)
                    .addComponent(lblGold))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDefensa)
                    .addComponent(lblLoot))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAtaque;
    private javax.swing.JLabel lblDefensa;
    private javax.swing.JLabel lblGold;
    private javax.swing.JLabel lblHP;
    private javax.swing.JLabel lblLoot;
    private javax.swing.JLabel lblMP;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSkill;
    private javax.swing.JLabel lblSkillCost;
    private javax.swing.JLabel lblSkillDamage;
    // End of variables declaration//GEN-END:variables
}
