/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.myst;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.util.Map;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class DialogPanel extends javax.swing.JPanel {
    /**
     * Creates new form CharacterPanel
     * @param dialogue
     * @param misiones
     */
    public DialogPanel(Dialogo dialogue/*, Map<String, Mision> misiones*/) {
        initComponents();
        setDatos(dialogue);
        setBorder(javax.swing.BorderFactory.createTitledBorder("Diálogo"));
        
    }

    public void setDatos(Dialogo dialogo) {
        //lblTexto.setText(dialogo.name);
        lblTexto.setText(dialogo.text);
        
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        
        jPanel1.removeAll();
        for (Map.Entry<String, String> entry : dialogo.options.entrySet()) {
            JButton btn = new JButton(entry.getKey());
            btn.setAlignmentX(Component.LEFT_ALIGNMENT);
            
            // Estilo consistente con NetBeans
            btn.setFont(new java.awt.Font("Segoe UI", 0, 12));
            btn.setMargin(new java.awt.Insets(2, 5, 2, 5));
            
            if (entry.getValue() != null) {
                btn.setToolTipText("Conduce a: " + entry.getValue());
                btn.addActionListener(e -> {
                    // Buscar la misión correspondiente
                    for (Mision m : MainFrame.misiones) {
                        if (m.name.equals(entry.getValue())) {
                            MissionPanel mp = new MissionPanel(m);
                            JOptionPane.showMessageDialog(this, mp, 
                                "Misión: " + m.name, 
                                JOptionPane.PLAIN_MESSAGE);
                            break;
                        }
                    }
                });
            }
            
            jPanel1.add(btn);
            jPanel1.add(Box.createRigidArea(new Dimension(0, 5)));  // Espaciado
        }
        
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTexto = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Dialog"));

        lblTexto.setText("Gracias por salvar a nuestro pueblo!!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(75, 75, 75))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTexto;
    // End of variables declaration//GEN-END:variables
}
