/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.myst;

import java.util.Map;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class DialogPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form CharacterPanel
     * @param dialogue
     * @param misiones
     */
    public DialogPanel(Dialogo dialogue, Map<String, Mision> misiones) {
        //initComponents();
        //setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        add(new JLabel("Nombre: " + (dialogue.name != null ? dialogue.name : "undefined")));
        add(new JLabel("Texto: " + (dialogue.text != null ? dialogue.text : "undefined")));

        /*for (Map.Entry<String, String> opcion : dialogue.options.entrySet()) {
            String label = opcion.getKey();
            String misionReferida = opcion.getValue();

            JButton boton = new JButton(label);
            boton.addActionListener(e -> {
                if (misiones.containsKey(misionReferida)) {
                    Mision mision = misiones.get(misionReferida);
                    MissionPanel mp = new MissionPanel(mision);
                    VistaCompleta vc = new VistaCompleta();
                    vc.getPanelContenedor().add(mp);
                    vc.pack();
                    vc.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "La misión '" + misionReferida + "' no existe.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            });

            add(boton);
        }*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTexto = new javax.swing.JLabel();
        jOpcion1 = new javax.swing.JButton();
        jOpcion2 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Dialog"));

        lblTexto.setText("Gracias por salvar a nuestro pueblo!!");

        jOpcion1.setText("Opción 1");
        jOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOpcion1ActionPerformed(evt);
            }
        });

        jOpcion2.setText("Opción 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jOpcion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jOpcion2)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jOpcion1)
                    .addComponent(jOpcion2))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOpcion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jOpcion1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jOpcion1;
    private javax.swing.JButton jOpcion2;
    private javax.swing.JLabel lblTexto;
    // End of variables declaration//GEN-END:variables
}
