/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.myst;

/**
 *
 * @author Rodrigo
 */
public class EnemyPanel extends javax.swing.JPanel {

    /**
     * Creates new form CharacterPanel
     */
    public EnemyPanel(Enemigo en) {
        initComponents();
        
        lblNombre.setText("Nombre: " + en.name);
        lblHP.setText("HP: " + en.hp);
        lblAtaque.setText("Ataque: " + en.attack);
        lblDefensa.setText("Defensa: " + en.defense);
        lblGold.setText("Gold: " + en.gold);
        lblLoot.setText("Loot: " + en.loot);
    }
    
    public void setDatos(Enemigo en) {
        lblNombre.setText("Nombre: " + en.name);
        lblHP.setText("HP: " + en.hp);
        lblAtaque.setText("Ataque: " + en.attack);
        lblDefensa.setText("Defensa: " + en.defense);
        lblGold.setText("Gold: " + en.gold);
        lblLoot.setText("Loot: " + en.loot);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblHP = new javax.swing.JLabel();
        lblAtaque = new javax.swing.JLabel();
        lblDefensa = new javax.swing.JLabel();
        lblGold = new javax.swing.JLabel();
        lblLoot = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Enemy"));

        lblNombre.setText("Nombre: ");

        lblHP.setText("HP: ");

        lblAtaque.setText("Ataque: ");

        lblDefensa.setText("Defensa: ");

        lblGold.setText("Gold: ");

        lblLoot.setText("Loot: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblNombre))
                    .addComponent(lblGold)
                    .addComponent(lblLoot))
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDefensa)
                    .addComponent(lblAtaque)
                    .addComponent(lblHP))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblHP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAtaque)
                    .addComponent(lblGold))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoot)
                    .addComponent(lblDefensa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAtaque;
    private javax.swing.JLabel lblDefensa;
    private javax.swing.JLabel lblGold;
    private javax.swing.JLabel lblHP;
    private javax.swing.JLabel lblLoot;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
