/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.myst;

/**
 *
 * @author Rodrigo
 */
public class MissionPanel extends javax.swing.JPanel {

    /**
     * Creates new form CharacterPanel
     */
    public MissionPanel(Mision m) {
        initComponents();
        
        lblName.setText("Nombre: " + m.name);
        lblGoal.setText("Objetivo: " + m.goal);
        lblReward.setText("Recompensa: " + m.reward);
    }
    
    public void setDatos(Mision m) {
        lblName.setText("Nombre: " + m.name);
        lblGoal.setText("Objetivo: " + m.goal);
        lblReward.setText("Recompensa: " + m.reward);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGoal = new javax.swing.JLabel();
        lblReward = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Misión"));

        lblGoal.setText("Objetivo: ");

        lblReward.setText("Recompensa:");

        lblName.setText("Nombre: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReward)
                    .addComponent(lblGoal)
                    .addComponent(lblName))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(lblName)
                .addGap(12, 12, 12)
                .addComponent(lblGoal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblReward)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblGoal;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblReward;
    // End of variables declaration//GEN-END:variables
}
