
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.myst;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int OPTION = 17;
  public static final int SKILL = 13;
  public static final int LOOT = 10;
  public static final int CHARACTER = 2;
  public static final int LLO = 22;
  public static final int END = 19;
  public static final int QUEST = 4;
  public static final int DEFENSE = 9;
  public static final int COLON = 21;
  public static final int ID = 26;
  public static final int LLC = 23;
  public static final int STRING = 24;
  public static final int OBJECTIVE = 12;
  public static final int MP = 7;
  public static final int NUMBER = 25;
  public static final int EOF = 0;
  public static final int ENEMY = 3;
  public static final int GOLD = 16;
  public static final int ARROW = 20;
  public static final int error = 1;
  public static final int START = 18;
  public static final int HP = 6;
  public static final int ATTACK = 8;
  public static final int REWARD = 11;
  public static final int DIALOGUE = 5;
  public static final int DAMAGE = 14;
  public static final int MP_COST = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CHARACTER",
  "ENEMY",
  "QUEST",
  "DIALOGUE",
  "HP",
  "MP",
  "ATTACK",
  "DEFENSE",
  "LOOT",
  "REWARD",
  "OBJECTIVE",
  "SKILL",
  "DAMAGE",
  "MP_COST",
  "GOLD",
  "OPTION",
  "START",
  "END",
  "ARROW",
  "COLON",
  "LLO",
  "LLC",
  "STRING",
  "NUMBER",
  "ID"
  };
}

